### ISSUE TITLE
Can't find boost/filesystem.hpp

### ISSUE THREAD

**Issue by coryl** [jing-interactive/FaceVFX#2]
I'm having trouble building the xcode iOS project. It seems it can't find the file reference for boost.

Its not included in the project or git, where can I get this repo/framework? Thanks

**Comment by vinjn** [comment]
Check readme for dependent building blocks.

**Comment by coryl** [comment]
ReadME doesn't mention anything about boost.

**Comment by vinjn** [comment]
boost is self contained in cinder

**Comment by vinjn** [comment]
https://github.com/vnm-interactive/Cinder/tree/master/include
