### ISSUE TITLE
Able to build, runs on Mac but not iOS

### ISSUE THREAD

**Issue by coryl** [jing-interactive/FaceVFX#3]
Hi there, I was able to build the project with Xcode for mac and iOS. To do this however I ran into a couple issues which others may run into:

1) The Xcode project was still looking for a file called MiniConfigImgui.cpp. This can be removed from the project in 'build phases' > 'compile sources'.

2) The project also looks for 'libcinder-iphone_d.a' and 'libcinder-iphone-sim_d.a' in Cinder/lib/, but those files aren't included in the Cinder readme git repo. To get those files I just downloaded the zip from https://libcinder.org/download and they were included, just copied them over.

3) Run the xcode project in Cinder/xcode (or run fullbuild.sh).

Anyhow that gets me to now: the project runs great on Mac. However running on iPhone gets an immediate crash:

FaceVFX(6093,0x1a1c4e000) malloc: **\* error for object 0x182e14d00: pointer being freed was not allocated
**\* set a breakpoint in malloc_error_break to debug

Thanks for your help and efforts!

**Comment by vinjn** [comment]
Thanks for pointing out, I should remove reference to MiniConfigImgui.cpp.
`libcinder-iphone_d.a' and 'libcinder-iphone-sim_d.a' are generated by`fullbuild.sh`

iOS build works for me.

**Comment by couleurs** [comment]
I'm having problem building on Mac due to OpenCV issues. @coryl  Any specific steps you had to take to make this aspect work? Thanks!

**Comment by couleurs** [comment]
nvm I was able to build on MacOS. Didn't realize that the Cinder OpenCV block already included all the opencv headers and binaries :p

**Comment by JoeriBultheel** [comment]
I would love a clear step by step installation guide... What are the dependencies? Where to get them? How to install them. Just listing the dependencies isn't very productive (and I'm running into issues now).

Thnx! (looks great)

**Comment by JoeriBultheel** [comment]
To be more specific. These are the linking issues I have now (MacOS)

Undefined symbols for architecture x86_64:
  "cinder::detail::assertionFailedAbort(char const*, char const*, char const*, long)", referenced from:
      cinder::signals::detail::SignalLinkBase::incrRef() in MiniConfig.o
      cinder::signals::detail::SignalLinkBase::~SignalLinkBase() in MiniConfig.o
      cinder::signals::detail::SignalLinkBase::decrRef() in MiniConfig.o
      ImGui::PushFont(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in CinderImGui.o
  "cinder::SurfaceT<unsigned char>::SurfaceT(std::__1::shared_ptr<cinder::ImageSource>, cinder::SurfaceConstraints const&)", referenced from:
      FaceOff::updateOfflineImage(std::__1::shared_ptr<cinder::ImageSource>) in FaceVFXApp.o
      std::__1::shared_ptr<cinder::SurfaceT<unsigned char> > std::__1::shared_ptr<cinder::SurfaceT<unsigned char> >::make_shared<std::__1::shared_ptr<cinder::ImageSource>&, cinder::SurfaceConstraints const&>(std::__1::shared_ptr<cinder::ImageSource>&&&, cinder::SurfaceConstraints const&&&) in AssetManager.o
     (maybe you meant: __ZN6cinder8SurfaceTIhEC1ENSt3__110shared_ptrINS_11ImageSourceEEERKNS_18SurfaceConstraintsEN5boost5logic7triboolE)
  "cinder::app::AppBase::get()", referenced from:
      cinder::app::copyWindowSurface() in MiniConfig.o
      cinder::app::getAppPath() in MiniConfig.o
      cinder::app::getElapsedFrames() in MiniConfig.o
      cinder::app::getWindow() in MiniConfig.o
      createConfigUI(glm::tvec2<int, (glm::precision)0> const&)::$_0::operator()() const in MiniConfig.o
      ImGui::initialize(ImGui::Options const&) in CinderImGui.o
      ImGui::(anonymous namespace)::render() in CinderImGui.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JoeriBultheel** [comment]
Fixed it by running Cider's fullbuild.sh script! 

Thnx for the awesome project!

**Comment by vinjn** [comment]
I am glad you like it!
