### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by JoeriBultheel** [jing-interactive/FaceVFX#4]
Hello,

I have successfully installed FaceVFX in the past, but now on another computer I am facing installation issues.

I cloned FaceVFX together with all the dependencies. I mirrored the file structure as described on this github page. I also cloned imgui and boost in their respective folders ( Cinder/blocks/Cinder-ImGui/lib/imgui and Cinder/include/boost) because they are subdirectories. I ran the Cinder xcode project and it was succesfully build. Now when I try to run the FaceVFX project in xcode it tells me following warnings:

Semantic issues:

Call to 'ColorPicker3' is ambiguous (in CinderImGui.h)
Call to 'ColorPicker4' is ambiguous (in CinderImGui.h)
No member named 'ButtonRepeat' in 'imGuiDrawContext' CinderImGui.cpp

What am i doing wrong? Any help much appreciated! Thnx

**Comment by JoeriBultheel** [comment]
I was able to supress some warnings by downloading a zip of the imgui project at the specific commit you used. I think previously I got the latest commit by cloning it, which had some new conflicting changes. However, for the boost dependency. I don't know at which commit i should download it since the boost itself is a dependency of a dependency (of Cinder). 

Could you try to install FaceVFX again from scratch and see if you run into the same problems as mee? Thnx!

**Comment by vinjn** [comment]
You should update sub-modules like `boost` and `imgui` via
`git submodule update --init --recursive` in `Cinder` and `Cinder-Imgui` folders.

**Comment by JoeriBultheel** [comment]
Ok I used the git submodule update command, 
Now I am able to run the project, but I immediately get a runtime error: 
**Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)** in operations.hpp on line 404.

in method boost::filesystem::exists(boost::fill::filesystem::path const&)

https://imgur.com/a/HJZLR

Thank you for the fast response!

**Comment by JoeriBultheel** [comment]
I deleted everything and installed everything anew. Now it worked. Thanks!

**Comment by vinjn** [comment]
Closing...
